include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    camel_case_types: true
    prefer_void_to_null: true
    void_checks: true
    omit_local_variable_types: false
    prefer_single_quotes: false
